import {
	defineStore
} from 'pinia';

export const useStore = defineStore('main', {
	state: () => ({
		userInfo: {
			uid: 0,
			instId: 1,
			userId: "",
			password: "",
			salt: "",
			idCard: null,
			idCode: "",
			idStatusDesc: "",
			idActivationDate: "",
			idExpireDate: "",
			idStatus: 0,
			idUpdatedBy: null,
			idUpdatedDate: null,
			firstName: null,
			middleName: null,
			lastName: null,
			displayName: "",
			gender: 0,
			genderDesc: "",
			birthday: "",
			nation: null,
			dept: "",
			occupation: "",
			duty: null,
			jobPost: null,
			education: "",
			address: "",
			phone: null,
			email: null,
			mobile: "",
			userType: "",
			userGroup: "",
			userGroupDesc: "",
			department: "",
			grade: "",
			isRoot: 0,
			isCheckedEmail: 0,
			isLoginRestrict: 0,
			isLoginRestrictDesc: null,
			regDate: "",
			logoutDate: null,
			expireDate: "",
			isNeedEditpwd: 0,
			isNeedEditpwdDesc: null,
			isLoginLimit: 0,
			isIpopen: 0,
			obligate: 0,
			deposit: 0,
			serviceCharge: 0,
			voucher: 0,
			credit: 0,
			userStatus: 0,
			userClass: "",
			userCountry: null,
			userStatusDesc: "",
			catalogLevel: 0,
			loginLimitTime: null,
			libCode: "",
			libPath: "",
			loginNum: 0,
			note: null,
			lastLoginTime: null,
			statusUpdatedBy: null,
			statusUpdatedDate: null,
			createdDate: "",
			updatedBy: "",
			updatedDate: "",
			userRoles: null,
			userIdentifiers: null,
			userExinfos: null,
			photoName: null,
			loanedCount: 0,
			maxLoanCount: 0,
			userTypeDesc: null,
		},
		loginState: false,
		// 页面间传参：搜索的词，选择的类型
		pages: {
			searchValue: "",
			choiceType: ""
		},

	}),
	actions: {
		setloginState(state : Boolean) {
			this.loginState = state
		}
	},
});